/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Bidirectional handle to a running exec: write stdin, read events via `next()`. */
export declare class ExecHandle {
  write(data: Buffer): Promise<void>
  eof(): Promise<void>
  signal(sig: number): Promise<void>
  resize(cols: number, rows: number): Promise<void>
  /** The next event, or `null` when the exec stream ends. */
  next(): Promise<ExecEventJs | null>
}

/** A local host-port forward into a guest port. Close it to release the listener. */
export declare class ForwardHandle {
  get guestPort(): number
  get hostPort(): number
  close(): Promise<void>
}

/** A connection to a Chevalier sandbox provider. */
export declare class Sandbox {
  /** Connect to a sandbox provider. */
  static connect(endpoint: string, options?: SandboxConnectOptions | undefined | null): Promise<Sandbox>
  /** Create a new session (microVM). */
  session(options?: SessionOpts | undefined | null): Promise<Session>
  /** Attach to an existing session by id. */
  attachSession(sessionId: string): Promise<Session>
  /** Attach without restoring, starting, or probing the VM. */
  attachSessionPassive(sessionId: string): Promise<Session>
  /** List live sessions visible to this sandbox provider. */
  listSessions(): Promise<Array<SessionInfoJs>>
  listDurableVolumes(): Promise<Array<DurableVolumeInfoJs>>
  deleteDurableVolume(ownerKey: string): Promise<void>
  resizeDurableVolume(ownerKey: string, sizeGb: number): Promise<DurableVolumeInfoJs>
  listHostPciDevices(): Promise<HostPciInventoryJs>
  /** Discard a provider session by id, even if this process does not hold a Session handle. */
  discardSessionById(sessionId: string): Promise<void>
}

/** A sandbox session (one microVM). */
export declare class Session {
  get sessionId(): string
  get vmId(): string
  get workspaceRoot(): string
  /** Start a command; returns a bidirectional `ExecHandle`. */
  exec(command: string, options?: ExecOpts | undefined | null): Promise<ExecHandle>
  /** Start an interactive PTY shell; returns a bidirectional `ShellHandle`. */
  shell(options?: ShellOpts | undefined | null): Promise<ShellHandle>
  /** Read a file from the guest. */
  readFile(path: string): Promise<Buffer>
  /** List a directory through the guest's mounted filesystem. */
  listDir(path: string): Promise<Array<SessionDirectoryEntryJs>>
  /** Write a file to the guest. */
  writeFile(path: string, data: Buffer): Promise<void>
  /** Stream a host-local file into the guest and atomically replace `path`. */
  writeFileFromFile(path: string, sourcePath: string, mode?: number | undefined | null): Promise<void>
  /** Fork this session (CoW); returns the child session. */
  fork(options?: ForkOpts | undefined | null): Promise<Session>
  /** Create a checkpoint/snapshot for this session. */
  checkpoint(name: string): Promise<SessionCheckpointJs>
  /** Restore a checkpoint into a new session. */
  restoreCheckpoint(checkpointId: string): Promise<Session>
  /** Read the current VM state from the sandbox provider. */
  getState(): Promise<string>
  updateResources(options: SessionResourceOptions): Promise<string>
  reconfigureSharedMounts(sharedMounts: Array<SharedMountOpts>): Promise<string>
  listPciDevices(): Promise<HostPciInventoryJs>
  attachPciDevice(deviceId: string): Promise<PciDeviceActionJs>
  detachPciDevice(deviceId: string): Promise<PciDeviceActionJs>
  /** Pause the VM without deleting it. */
  pause(): Promise<string>
  start(): Promise<string>
  restart(): Promise<string>
  /** Resume a paused VM. */
  resume(): Promise<string>
  /** Stop the VM without deleting its record. */
  stop(): Promise<string>
  /** Create a VM snapshot/checkpoint. */
  snapshot(options?: SessionSnapshotOpts | undefined | null): Promise<SessionSnapshotJs>
  /** Restore this VM from a snapshot. */
  restore(snapshotId: string): Promise<string>
  /** List snapshots for this VM. */
  listSnapshots(): Promise<Array<SessionSnapshotJs>>
  /** Delete a VM snapshot. */
  deleteSnapshot(snapshotId: string): Promise<void>
  /** Forward a guest TCP port to a local host port. */
  forwardPort(guestPort: number): Promise<ForwardHandle>
  /** Return a provider-managed preview URL when the provider supports one. */
  providerPreviewUrl(guestPort: number): Promise<string>
  /** Open this VM's desktop. QEMU guests return a VNC target; macOS VZ opens a native viewer window. */
  openDesktop(): Promise<SessionDesktopTargetJs>
  /** Close a provider-owned desktop window without stopping the VM. */
  closeDesktop(): Promise<void>
  /** Close the session handle without deleting the VM. */
  close(): Promise<void>
  /** Delete the backing VM/sandbox and purge provider resources. */
  discard(): Promise<void>
}

/** Bidirectional handle to a running interactive PTY shell. */
export declare class ShellHandle {
  write(data: Buffer): Promise<void>
  eof(): Promise<void>
  resize(cols: number, rows: number): Promise<void>
  /** The next shell event, or `null` when the shell stream ends. */
  next(): Promise<ShellEventJs | null>
}

export interface DistributedControlOptions {
  etcdEndpoints: Array<string>
  natsUrl: string
  etcdPrefix?: string
  clusterId?: string
  natsAuthToken?: string
  requiredContinuityTier?: string
  requiredStorageProfile?: string
  allowTierADegraded?: boolean
  allowCrossNodeRecovery?: boolean
  natsStreamReplicas?: number
}

export interface DurableVolumeInfoJs {
  ownerKey: string
  volumeId: string
  sizeGb: number
  createdAtMs: number
  updatedAtMs: number
  backingVolumeId?: string
  attachedVmIds: Array<string>
}

/** A single exec event. `type` is `stdout` | `stderr` | `exit` | `timeout`. */
export interface ExecEventJs {
  type: string
  data?: Buffer
  code?: number
}

export interface ExecOpts {
  env?: Record<string, string>
  timeoutSecs?: number
  detach?: boolean
  shell?: string
  closeStdinOnStart?: boolean
}

export interface ForkOpts {
  childName?: string
  childMetadata?: Record<string, string>
  autoStartChild?: boolean
}

export interface HostPciDeviceJs {
  id: string
  label: string
  functions: Array<HostPciFunctionJs>
  state: string
  assignedVmId: string
  managed: boolean
  hotplugCapable: boolean
  unavailableReason: string
}

export interface HostPciFunctionJs {
  bdf: string
  vendorId: string
  deviceId: string
  classCode: string
  driver: string
  iommuGroup: string
}

export interface HostPciInventoryJs {
  enabled: boolean
  devices: Array<HostPciDeviceJs>
}

export interface OpenComputerMountOpts {
  path?: string
  driver?: string
  remote?: string
  backend?: string
  command?: Array<string>
  env?: Record<string, string>
  secrets?: Record<string, string>
  creds?: Record<string, string>
  rcloneConfig?: string
  readOnly?: boolean
  mountOptions?: Array<string>
}

export interface OpenComputerProviderOpts {
  apiUrl?: string
  apiKey?: string
  templateId?: string
  timeoutSecs?: number
  defaultCpuCount?: number
  defaultMemoryMb?: number
  defaultDiskMb?: number
  burst?: boolean
  secretStore?: string
  egressAllowlist?: Array<string>
  mounts?: Array<OpenComputerMountOpts>
  sharedMounts?: Record<string, OpenComputerMountOpts>
}

export interface PciDeviceActionJs {
  device?: HostPciDeviceJs
  restartRequired: boolean
  detail: string
  vmState: string
}

export interface SandboxConnectOptions {
  authToken?: string
  pciAccessToken?: string
  connectTimeoutMs?: number
  defaultImage?: string
  defaultArchitecture?: string
  defaultVcpu?: number
  defaultMemoryMb?: number
  defaultDiskGb?: number
  provider?: string
  openComputer?: OpenComputerProviderOpts
  distributedControl?: DistributedControlOptions
}

export interface SessionCheckpointJs {
  id: string
}

export interface SessionDesktopTargetJs {
  kind: "vnc" | "native-window"
  host?: string
  port?: number
  password?: string
  authentication: "none" | "password" | "account"
  viewOnly: boolean
}

/** One entry returned by `Session.listDir`. */
export interface SessionDirectoryEntryJs {
  name: string
  isDir: boolean
  isSymlink: boolean
}

export interface SessionInfoJs {
  sessionId: string
  vmId: string
  name: string
  state: number
  parentSessionId?: string
  forkId?: string
}

export interface SessionOpts {
  sessionId?: string
  name?: string
  image?: string
  sourceType?: SessionSourceType
  architecture?: string
  metadata?: Record<string, string>
  autoStart?: boolean
  sharedMounts?: Array<SharedMountOpts>
  egressAllowlist?: Array<string>
  pciDeviceIds?: Array<string>
  storageProfile?: string
  volumeOwnerKey?: string
  volumeSizeGb?: number
}

export interface SessionResourceOptions {
  vcpu?: number
  memoryMb?: number
}

export interface SessionSnapshotJs {
  id: string
  name: string
  label: string
  description: string
}

export interface SessionSnapshotOpts {
  label?: string
  description?: string
}

export declare const enum SessionSourceType {
  Docker = 'docker',
  Snapshot = 'snapshot',
  MacosTemplate = 'macos-template',
  WindowsTemplate = 'windows-template'
}

export interface SharedMountOpts {
  hostPath?: string
  guestPath: string
  mountTag: string
  readOnly?: boolean
  availability?: string
  continuity?: string
  backendProfile?: string
  vfsEndpoint?: string
  vfsScopePath?: string
}

/** A single interactive shell event. `type` is `output` | `exit`. */
export interface ShellEventJs {
  type: string
  data?: Buffer
  code?: number
}

export interface ShellOpts {
  shell?: string
  args?: Array<string>
  env?: Record<string, string>
  cwd?: string
  cols?: number
  rows?: number
}
