// @dive-file: Portproxy gRPC contract for guest-side file, exec, shell, and daemon attachment services.
// @dive-rel: Generated by portproxy/build.rs and vmd/build.rs for guest runtime and node-local client use.
// @dive-rel: Defines streaming/daemon attach semantics used by distributed exec producer rebind paths.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: bracket/portproxy/v1/portproxy.proto

package portproxyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecDaemonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timeout       *int32                 `protobuf:"varint,4,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	Detach        bool                   `protobuf:"varint,5,opt,name=detach,proto3" json:"detach,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecDaemonRequest) Reset() {
	*x = ExecDaemonRequest{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecDaemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecDaemonRequest) ProtoMessage() {}

func (x *ExecDaemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecDaemonRequest.ProtoReflect.Descriptor instead.
func (*ExecDaemonRequest) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{0}
}

func (x *ExecDaemonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecDaemonRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecDaemonRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecDaemonRequest) GetTimeout() int32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

func (x *ExecDaemonRequest) GetDetach() bool {
	if x != nil {
		return x.Detach
	}
	return false
}

type ExecDaemonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsNew         bool                   `protobuf:"varint,1,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecDaemonResponse) Reset() {
	*x = ExecDaemonResponse{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecDaemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecDaemonResponse) ProtoMessage() {}

func (x *ExecDaemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecDaemonResponse.ProtoReflect.Descriptor instead.
func (*ExecDaemonResponse) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{1}
}

func (x *ExecDaemonResponse) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

type AttachDaemonRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*AttachDaemonRequest_Start
	//	*AttachDaemonRequest_StdinData
	Request       isAttachDaemonRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDaemonRequest) Reset() {
	*x = AttachDaemonRequest{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDaemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDaemonRequest) ProtoMessage() {}

func (x *AttachDaemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDaemonRequest.ProtoReflect.Descriptor instead.
func (*AttachDaemonRequest) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{2}
}

func (x *AttachDaemonRequest) GetRequest() isAttachDaemonRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AttachDaemonRequest) GetStart() *AttachDaemonStart {
	if x != nil {
		if x, ok := x.Request.(*AttachDaemonRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *AttachDaemonRequest) GetStdinData() []byte {
	if x != nil {
		if x, ok := x.Request.(*AttachDaemonRequest_StdinData); ok {
			return x.StdinData
		}
	}
	return nil
}

type isAttachDaemonRequest_Request interface {
	isAttachDaemonRequest_Request()
}

type AttachDaemonRequest_Start struct {
	Start *AttachDaemonStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type AttachDaemonRequest_StdinData struct {
	StdinData []byte `protobuf:"bytes,2,opt,name=stdin_data,json=stdinData,proto3,oneof"`
}

func (*AttachDaemonRequest_Start) isAttachDaemonRequest_Request() {}

func (*AttachDaemonRequest_StdinData) isAttachDaemonRequest_Request() {}

type AttachDaemonStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDaemonStart) Reset() {
	*x = AttachDaemonStart{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDaemonStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDaemonStart) ProtoMessage() {}

func (x *AttachDaemonStart) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDaemonStart.ProtoReflect.Descriptor instead.
func (*AttachDaemonStart) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{3}
}

func (x *AttachDaemonStart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AttachDaemonResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*AttachDaemonResponse_StdoutData
	//	*AttachDaemonResponse_StderrData
	//	*AttachDaemonResponse_ExitCode
	Response      isAttachDaemonResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDaemonResponse) Reset() {
	*x = AttachDaemonResponse{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDaemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDaemonResponse) ProtoMessage() {}

func (x *AttachDaemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDaemonResponse.ProtoReflect.Descriptor instead.
func (*AttachDaemonResponse) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{4}
}

func (x *AttachDaemonResponse) GetResponse() isAttachDaemonResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *AttachDaemonResponse) GetStdoutData() []byte {
	if x != nil {
		if x, ok := x.Response.(*AttachDaemonResponse_StdoutData); ok {
			return x.StdoutData
		}
	}
	return nil
}

func (x *AttachDaemonResponse) GetStderrData() []byte {
	if x != nil {
		if x, ok := x.Response.(*AttachDaemonResponse_StderrData); ok {
			return x.StderrData
		}
	}
	return nil
}

func (x *AttachDaemonResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Response.(*AttachDaemonResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isAttachDaemonResponse_Response interface {
	isAttachDaemonResponse_Response()
}

type AttachDaemonResponse_StdoutData struct {
	StdoutData []byte `protobuf:"bytes,1,opt,name=stdout_data,json=stdoutData,proto3,oneof"`
}

type AttachDaemonResponse_StderrData struct {
	StderrData []byte `protobuf:"bytes,2,opt,name=stderr_data,json=stderrData,proto3,oneof"`
}

type AttachDaemonResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*AttachDaemonResponse_StdoutData) isAttachDaemonResponse_Response() {}

func (*AttachDaemonResponse_StderrData) isAttachDaemonResponse_Response() {}

func (*AttachDaemonResponse_ExitCode) isAttachDaemonResponse_Response() {}

type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ExecRequest_Start
	//	*ExecRequest_StdinData
	Request       isExecRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{5}
}

func (x *ExecRequest) GetRequest() isExecRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExecRequest) GetStart() *ExecStart {
	if x != nil {
		if x, ok := x.Request.(*ExecRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecRequest) GetStdinData() []byte {
	if x != nil {
		if x, ok := x.Request.(*ExecRequest_StdinData); ok {
			return x.StdinData
		}
	}
	return nil
}

type isExecRequest_Request interface {
	isExecRequest_Request()
}

type ExecRequest_Start struct {
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecRequest_StdinData struct {
	StdinData []byte `protobuf:"bytes,2,opt,name=stdin_data,json=stdinData,proto3,oneof"`
}

func (*ExecRequest_Start) isExecRequest_Request() {}

func (*ExecRequest_StdinData) isExecRequest_Request() {}

type ExecStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Detach        bool                   `protobuf:"varint,3,opt,name=detach,proto3" json:"detach,omitempty"`
	Timeout       *int32                 `protobuf:"varint,4,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{6}
}

func (x *ExecStart) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecStart) GetDetach() bool {
	if x != nil {
		return x.Detach
	}
	return false
}

func (x *ExecStart) GetTimeout() int32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ExecResponse_StdoutData
	//	*ExecResponse_StderrData
	//	*ExecResponse_ExitCode
	Response      isExecResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{7}
}

func (x *ExecResponse) GetResponse() isExecResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ExecResponse) GetStdoutData() []byte {
	if x != nil {
		if x, ok := x.Response.(*ExecResponse_StdoutData); ok {
			return x.StdoutData
		}
	}
	return nil
}

func (x *ExecResponse) GetStderrData() []byte {
	if x != nil {
		if x, ok := x.Response.(*ExecResponse_StderrData); ok {
			return x.StderrData
		}
	}
	return nil
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Response.(*ExecResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isExecResponse_Response interface {
	isExecResponse_Response()
}

type ExecResponse_StdoutData struct {
	StdoutData []byte `protobuf:"bytes,1,opt,name=stdout_data,json=stdoutData,proto3,oneof"`
}

type ExecResponse_StderrData struct {
	StderrData []byte `protobuf:"bytes,2,opt,name=stderr_data,json=stderrData,proto3,oneof"`
}

type ExecResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*ExecResponse_StdoutData) isExecResponse_Response() {}

func (*ExecResponse_StderrData) isExecResponse_Response() {}

func (*ExecResponse_ExitCode) isExecResponse_Response() {}

type InteractiveShellRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*InteractiveShellRequest_Start
	//	*InteractiveShellRequest_StdinData
	//	*InteractiveShellRequest_Resize
	Request       isInteractiveShellRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractiveShellRequest) Reset() {
	*x = InteractiveShellRequest{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractiveShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractiveShellRequest) ProtoMessage() {}

func (x *InteractiveShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractiveShellRequest.ProtoReflect.Descriptor instead.
func (*InteractiveShellRequest) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{8}
}

func (x *InteractiveShellRequest) GetRequest() isInteractiveShellRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *InteractiveShellRequest) GetStart() *InteractiveShellStart {
	if x != nil {
		if x, ok := x.Request.(*InteractiveShellRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *InteractiveShellRequest) GetStdinData() []byte {
	if x != nil {
		if x, ok := x.Request.(*InteractiveShellRequest_StdinData); ok {
			return x.StdinData
		}
	}
	return nil
}

func (x *InteractiveShellRequest) GetResize() *InteractiveShellResize {
	if x != nil {
		if x, ok := x.Request.(*InteractiveShellRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isInteractiveShellRequest_Request interface {
	isInteractiveShellRequest_Request()
}

type InteractiveShellRequest_Start struct {
	Start *InteractiveShellStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type InteractiveShellRequest_StdinData struct {
	StdinData []byte `protobuf:"bytes,2,opt,name=stdin_data,json=stdinData,proto3,oneof"`
}

type InteractiveShellRequest_Resize struct {
	Resize *InteractiveShellResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*InteractiveShellRequest_Start) isInteractiveShellRequest_Request() {}

func (*InteractiveShellRequest_StdinData) isInteractiveShellRequest_Request() {}

func (*InteractiveShellRequest_Resize) isInteractiveShellRequest_Request() {}

type InteractiveShellStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shell         string                 `protobuf:"bytes,1,opt,name=shell,proto3" json:"shell,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd           string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractiveShellStart) Reset() {
	*x = InteractiveShellStart{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractiveShellStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractiveShellStart) ProtoMessage() {}

func (x *InteractiveShellStart) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractiveShellStart.ProtoReflect.Descriptor instead.
func (*InteractiveShellStart) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{9}
}

func (x *InteractiveShellStart) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *InteractiveShellStart) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *InteractiveShellStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *InteractiveShellStart) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

type InteractiveShellResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractiveShellResize) Reset() {
	*x = InteractiveShellResize{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractiveShellResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractiveShellResize) ProtoMessage() {}

func (x *InteractiveShellResize) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractiveShellResize.ProtoReflect.Descriptor instead.
func (*InteractiveShellResize) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{10}
}

func (x *InteractiveShellResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *InteractiveShellResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type InteractiveShellResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*InteractiveShellResponse_OutputData
	//	*InteractiveShellResponse_ExitCode
	Response      isInteractiveShellResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractiveShellResponse) Reset() {
	*x = InteractiveShellResponse{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractiveShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractiveShellResponse) ProtoMessage() {}

func (x *InteractiveShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractiveShellResponse.ProtoReflect.Descriptor instead.
func (*InteractiveShellResponse) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{11}
}

func (x *InteractiveShellResponse) GetResponse() isInteractiveShellResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *InteractiveShellResponse) GetOutputData() []byte {
	if x != nil {
		if x, ok := x.Response.(*InteractiveShellResponse_OutputData); ok {
			return x.OutputData
		}
	}
	return nil
}

func (x *InteractiveShellResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Response.(*InteractiveShellResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isInteractiveShellResponse_Response interface {
	isInteractiveShellResponse_Response()
}

type InteractiveShellResponse_OutputData struct {
	OutputData []byte `protobuf:"bytes,1,opt,name=output_data,json=outputData,proto3,oneof"`
}

type InteractiveShellResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*InteractiveShellResponse_OutputData) isInteractiveShellResponse_Response() {}

func (*InteractiveShellResponse_ExitCode) isInteractiveShellResponse_Response() {}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{12}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{13}
}

func (x *ReadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	CreateParents bool                   `protobuf:"varint,3,opt,name=create_parents,json=createParents,proto3" json:"create_parents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{14}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteFileRequest) GetCreateParents() bool {
	if x != nil {
		return x.CreateParents
	}
	return false
}

type ListDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryRequest) Reset() {
	*x = ListDirectoryRequest{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryRequest) ProtoMessage() {}

func (x *ListDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryRequest.ProtoReflect.Descriptor instead.
func (*ListDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{15}
}

func (x *ListDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DirectoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	IsSymlink     bool                   `protobuf:"varint,3,opt,name=is_symlink,json=isSymlink,proto3" json:"is_symlink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryEntry) Reset() {
	*x = DirectoryEntry{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryEntry) ProtoMessage() {}

func (x *DirectoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryEntry.ProtoReflect.Descriptor instead.
func (*DirectoryEntry) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{16}
}

func (x *DirectoryEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirectoryEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *DirectoryEntry) GetIsSymlink() bool {
	if x != nil {
		return x.IsSymlink
	}
	return false
}

type ListDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirectoryEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryResponse) Reset() {
	*x = ListDirectoryResponse{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryResponse) ProtoMessage() {}

func (x *ListDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryResponse.ProtoReflect.Descriptor instead.
func (*ListDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{17}
}

func (x *ListDirectoryResponse) GetEntries() []*DirectoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DeletePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePathRequest) Reset() {
	*x = DeletePathRequest{}
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePathRequest) ProtoMessage() {}

func (x *DeletePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bracket_portproxy_v1_portproxy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePathRequest.ProtoReflect.Descriptor instead.
func (*DeletePathRequest) Descriptor() ([]byte, []int) {
	return file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP(), []int{18}
}

func (x *DeletePathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_bracket_portproxy_v1_portproxy_proto protoreflect.FileDescriptor

const file_bracket_portproxy_v1_portproxy_proto_rawDesc = "" +
	"\n" +
	"$bracket/portproxy/v1/portproxy.proto\x12\x14bracket.portproxy.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xfa\x01\n" +
	"\x11ExecDaemonRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12B\n" +
	"\x03env\x18\x03 \x03(\v20.bracket.portproxy.v1.ExecDaemonRequest.EnvEntryR\x03env\x12\x1d\n" +
	"\atimeout\x18\x04 \x01(\x05H\x00R\atimeout\x88\x01\x01\x12\x16\n" +
	"\x06detach\x18\x05 \x01(\bR\x06detach\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_timeout\"+\n" +
	"\x12ExecDaemonResponse\x12\x15\n" +
	"\x06is_new\x18\x01 \x01(\bR\x05isNew\"\x82\x01\n" +
	"\x13AttachDaemonRequest\x12?\n" +
	"\x05start\x18\x01 \x01(\v2'.bracket.portproxy.v1.AttachDaemonStartH\x00R\x05start\x12\x1f\n" +
	"\n" +
	"stdin_data\x18\x02 \x01(\fH\x00R\tstdinDataB\t\n" +
	"\arequest\"'\n" +
	"\x11AttachDaemonStart\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x87\x01\n" +
	"\x14AttachDaemonResponse\x12!\n" +
	"\vstdout_data\x18\x01 \x01(\fH\x00R\n" +
	"stdoutData\x12!\n" +
	"\vstderr_data\x18\x02 \x01(\fH\x00R\n" +
	"stderrData\x12\x1d\n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCodeB\n" +
	"\n" +
	"\bresponse\"r\n" +
	"\vExecRequest\x127\n" +
	"\x05start\x18\x01 \x01(\v2\x1f.bracket.portproxy.v1.ExecStartH\x00R\x05start\x12\x1f\n" +
	"\n" +
	"stdin_data\x18\x02 \x01(\fH\x00R\tstdinDataB\t\n" +
	"\arequest\"\xd6\x01\n" +
	"\tExecStart\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x12:\n" +
	"\x03env\x18\x02 \x03(\v2(.bracket.portproxy.v1.ExecStart.EnvEntryR\x03env\x12\x16\n" +
	"\x06detach\x18\x03 \x01(\bR\x06detach\x12\x1d\n" +
	"\atimeout\x18\x04 \x01(\x05H\x00R\atimeout\x88\x01\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_timeout\"\x7f\n" +
	"\fExecResponse\x12!\n" +
	"\vstdout_data\x18\x01 \x01(\fH\x00R\n" +
	"stdoutData\x12!\n" +
	"\vstderr_data\x18\x02 \x01(\fH\x00R\n" +
	"stderrData\x12\x1d\n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCodeB\n" +
	"\n" +
	"\bresponse\"\xd2\x01\n" +
	"\x17InteractiveShellRequest\x12C\n" +
	"\x05start\x18\x01 \x01(\v2+.bracket.portproxy.v1.InteractiveShellStartH\x00R\x05start\x12\x1f\n" +
	"\n" +
	"stdin_data\x18\x02 \x01(\fH\x00R\tstdinData\x12F\n" +
	"\x06resize\x18\x03 \x01(\v2,.bracket.portproxy.v1.InteractiveShellResizeH\x00R\x06resizeB\t\n" +
	"\arequest\"\xd3\x01\n" +
	"\x15InteractiveShellStart\x12\x14\n" +
	"\x05shell\x18\x01 \x01(\tR\x05shell\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12F\n" +
	"\x03env\x18\x03 \x03(\v24.bracket.portproxy.v1.InteractiveShellStart.EnvEntryR\x03env\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x16InteractiveShellResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"h\n" +
	"\x18InteractiveShellResponse\x12!\n" +
	"\voutput_data\x18\x01 \x01(\fH\x00R\n" +
	"outputData\x12\x1d\n" +
	"\texit_code\x18\x02 \x01(\x05H\x00R\bexitCodeB\n" +
	"\n" +
	"\bresponse\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"&\n" +
	"\x10ReadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"a\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12%\n" +
	"\x0ecreate_parents\x18\x03 \x01(\bR\rcreateParents\"*\n" +
	"\x14ListDirectoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"Z\n" +
	"\x0eDirectoryEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x1d\n" +
	"\n" +
	"is_symlink\x18\x03 \x01(\bR\tisSymlink\"W\n" +
	"\x15ListDirectoryResponse\x12>\n" +
	"\aentries\x18\x01 \x03(\v2$.bracket.portproxy.v1.DirectoryEntryR\aentries\"'\n" +
	"\x11DeletePathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path2\xaf\x03\n" +
	"\tPortProxy\x12A\n" +
	"\x0fPrepareShutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12Y\n" +
	"\bReadFile\x12%.bracket.portproxy.v1.ReadFileRequest\x1a&.bracket.portproxy.v1.ReadFileResponse\x12K\n" +
	"\tWriteFile\x12&.bracket.portproxy.v1.WriteFileRequest\x1a\x16.google.protobuf.Empty\x12h\n" +
	"\rListDirectory\x12*.bracket.portproxy.v1.ListDirectoryRequest\x1a+.bracket.portproxy.v1.ListDirectoryResponse\x12M\n" +
	"\n" +
	"DeletePath\x12'.bracket.portproxy.v1.DeletePathRequest\x1a\x16.google.protobuf.Empty2\xd5\x01\n" +
	"\tShellExec\x12Q\n" +
	"\x04Exec\x12!.bracket.portproxy.v1.ExecRequest\x1a\".bracket.portproxy.v1.ExecResponse(\x010\x01\x12u\n" +
	"\x10InteractiveShell\x12-.bracket.portproxy.v1.InteractiveShellRequest\x1a..bracket.portproxy.v1.InteractiveShellResponse(\x010\x012\xdb\x01\n" +
	"\rDaemonManager\x12_\n" +
	"\n" +
	"ExecDaemon\x12'.bracket.portproxy.v1.ExecDaemonRequest\x1a(.bracket.portproxy.v1.ExecDaemonResponse\x12i\n" +
	"\fAttachDaemon\x12).bracket.portproxy.v1.AttachDaemonRequest\x1a*.bracket.portproxy.v1.AttachDaemonResponse(\x010\x01BQZOgithub.com/BracketDevelopers/OpenBracket/proto/bracket/portproxy/v1;portproxyv1b\x06proto3"

var (
	file_bracket_portproxy_v1_portproxy_proto_rawDescOnce sync.Once
	file_bracket_portproxy_v1_portproxy_proto_rawDescData []byte
)

func file_bracket_portproxy_v1_portproxy_proto_rawDescGZIP() []byte {
	file_bracket_portproxy_v1_portproxy_proto_rawDescOnce.Do(func() {
		file_bracket_portproxy_v1_portproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bracket_portproxy_v1_portproxy_proto_rawDesc), len(file_bracket_portproxy_v1_portproxy_proto_rawDesc)))
	})
	return file_bracket_portproxy_v1_portproxy_proto_rawDescData
}

var file_bracket_portproxy_v1_portproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_bracket_portproxy_v1_portproxy_proto_goTypes = []any{
	(*ExecDaemonRequest)(nil),        // 0: bracket.portproxy.v1.ExecDaemonRequest
	(*ExecDaemonResponse)(nil),       // 1: bracket.portproxy.v1.ExecDaemonResponse
	(*AttachDaemonRequest)(nil),      // 2: bracket.portproxy.v1.AttachDaemonRequest
	(*AttachDaemonStart)(nil),        // 3: bracket.portproxy.v1.AttachDaemonStart
	(*AttachDaemonResponse)(nil),     // 4: bracket.portproxy.v1.AttachDaemonResponse
	(*ExecRequest)(nil),              // 5: bracket.portproxy.v1.ExecRequest
	(*ExecStart)(nil),                // 6: bracket.portproxy.v1.ExecStart
	(*ExecResponse)(nil),             // 7: bracket.portproxy.v1.ExecResponse
	(*InteractiveShellRequest)(nil),  // 8: bracket.portproxy.v1.InteractiveShellRequest
	(*InteractiveShellStart)(nil),    // 9: bracket.portproxy.v1.InteractiveShellStart
	(*InteractiveShellResize)(nil),   // 10: bracket.portproxy.v1.InteractiveShellResize
	(*InteractiveShellResponse)(nil), // 11: bracket.portproxy.v1.InteractiveShellResponse
	(*ReadFileRequest)(nil),          // 12: bracket.portproxy.v1.ReadFileRequest
	(*ReadFileResponse)(nil),         // 13: bracket.portproxy.v1.ReadFileResponse
	(*WriteFileRequest)(nil),         // 14: bracket.portproxy.v1.WriteFileRequest
	(*ListDirectoryRequest)(nil),     // 15: bracket.portproxy.v1.ListDirectoryRequest
	(*DirectoryEntry)(nil),           // 16: bracket.portproxy.v1.DirectoryEntry
	(*ListDirectoryResponse)(nil),    // 17: bracket.portproxy.v1.ListDirectoryResponse
	(*DeletePathRequest)(nil),        // 18: bracket.portproxy.v1.DeletePathRequest
	nil,                              // 19: bracket.portproxy.v1.ExecDaemonRequest.EnvEntry
	nil,                              // 20: bracket.portproxy.v1.ExecStart.EnvEntry
	nil,                              // 21: bracket.portproxy.v1.InteractiveShellStart.EnvEntry
	(*emptypb.Empty)(nil),            // 22: google.protobuf.Empty
}
var file_bracket_portproxy_v1_portproxy_proto_depIdxs = []int32{
	19, // 0: bracket.portproxy.v1.ExecDaemonRequest.env:type_name -> bracket.portproxy.v1.ExecDaemonRequest.EnvEntry
	3,  // 1: bracket.portproxy.v1.AttachDaemonRequest.start:type_name -> bracket.portproxy.v1.AttachDaemonStart
	6,  // 2: bracket.portproxy.v1.ExecRequest.start:type_name -> bracket.portproxy.v1.ExecStart
	20, // 3: bracket.portproxy.v1.ExecStart.env:type_name -> bracket.portproxy.v1.ExecStart.EnvEntry
	9,  // 4: bracket.portproxy.v1.InteractiveShellRequest.start:type_name -> bracket.portproxy.v1.InteractiveShellStart
	10, // 5: bracket.portproxy.v1.InteractiveShellRequest.resize:type_name -> bracket.portproxy.v1.InteractiveShellResize
	21, // 6: bracket.portproxy.v1.InteractiveShellStart.env:type_name -> bracket.portproxy.v1.InteractiveShellStart.EnvEntry
	16, // 7: bracket.portproxy.v1.ListDirectoryResponse.entries:type_name -> bracket.portproxy.v1.DirectoryEntry
	22, // 8: bracket.portproxy.v1.PortProxy.PrepareShutdown:input_type -> google.protobuf.Empty
	12, // 9: bracket.portproxy.v1.PortProxy.ReadFile:input_type -> bracket.portproxy.v1.ReadFileRequest
	14, // 10: bracket.portproxy.v1.PortProxy.WriteFile:input_type -> bracket.portproxy.v1.WriteFileRequest
	15, // 11: bracket.portproxy.v1.PortProxy.ListDirectory:input_type -> bracket.portproxy.v1.ListDirectoryRequest
	18, // 12: bracket.portproxy.v1.PortProxy.DeletePath:input_type -> bracket.portproxy.v1.DeletePathRequest
	5,  // 13: bracket.portproxy.v1.ShellExec.Exec:input_type -> bracket.portproxy.v1.ExecRequest
	8,  // 14: bracket.portproxy.v1.ShellExec.InteractiveShell:input_type -> bracket.portproxy.v1.InteractiveShellRequest
	0,  // 15: bracket.portproxy.v1.DaemonManager.ExecDaemon:input_type -> bracket.portproxy.v1.ExecDaemonRequest
	2,  // 16: bracket.portproxy.v1.DaemonManager.AttachDaemon:input_type -> bracket.portproxy.v1.AttachDaemonRequest
	22, // 17: bracket.portproxy.v1.PortProxy.PrepareShutdown:output_type -> google.protobuf.Empty
	13, // 18: bracket.portproxy.v1.PortProxy.ReadFile:output_type -> bracket.portproxy.v1.ReadFileResponse
	22, // 19: bracket.portproxy.v1.PortProxy.WriteFile:output_type -> google.protobuf.Empty
	17, // 20: bracket.portproxy.v1.PortProxy.ListDirectory:output_type -> bracket.portproxy.v1.ListDirectoryResponse
	22, // 21: bracket.portproxy.v1.PortProxy.DeletePath:output_type -> google.protobuf.Empty
	7,  // 22: bracket.portproxy.v1.ShellExec.Exec:output_type -> bracket.portproxy.v1.ExecResponse
	11, // 23: bracket.portproxy.v1.ShellExec.InteractiveShell:output_type -> bracket.portproxy.v1.InteractiveShellResponse
	1,  // 24: bracket.portproxy.v1.DaemonManager.ExecDaemon:output_type -> bracket.portproxy.v1.ExecDaemonResponse
	4,  // 25: bracket.portproxy.v1.DaemonManager.AttachDaemon:output_type -> bracket.portproxy.v1.AttachDaemonResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_bracket_portproxy_v1_portproxy_proto_init() }
func file_bracket_portproxy_v1_portproxy_proto_init() {
	if File_bracket_portproxy_v1_portproxy_proto != nil {
		return
	}
	file_bracket_portproxy_v1_portproxy_proto_msgTypes[0].OneofWrappers = []any{}
	file_bracket_portproxy_v1_portproxy_proto_msgTypes[2].OneofWrappers = []any{
		(*AttachDaemonRequest_Start)(nil),
		(*AttachDaemonRequest_StdinData)(nil),
	}
	file_bracket_portproxy_v1_portproxy_proto_msgTypes[4].OneofWrappers = []any{
		(*AttachDaemonResponse_StdoutData)(nil),
		(*AttachDaemonResponse_StderrData)(nil),
		(*AttachDaemonResponse_ExitCode)(nil),
	}
	file_bracket_portproxy_v1_portproxy_proto_msgTypes[5].OneofWrappers = []any{
		(*ExecRequest_Start)(nil),
		(*ExecRequest_StdinData)(nil),
	}
	file_bracket_portproxy_v1_portproxy_proto_msgTypes[6].OneofWrappers = []any{}
	file_bracket_portproxy_v1_portproxy_proto_msgTypes[7].OneofWrappers = []any{
		(*ExecResponse_StdoutData)(nil),
		(*ExecResponse_StderrData)(nil),
		(*ExecResponse_ExitCode)(nil),
	}
	file_bracket_portproxy_v1_portproxy_proto_msgTypes[8].OneofWrappers = []any{
		(*InteractiveShellRequest_Start)(nil),
		(*InteractiveShellRequest_StdinData)(nil),
		(*InteractiveShellRequest_Resize)(nil),
	}
	file_bracket_portproxy_v1_portproxy_proto_msgTypes[11].OneofWrappers = []any{
		(*InteractiveShellResponse_OutputData)(nil),
		(*InteractiveShellResponse_ExitCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bracket_portproxy_v1_portproxy_proto_rawDesc), len(file_bracket_portproxy_v1_portproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_bracket_portproxy_v1_portproxy_proto_goTypes,
		DependencyIndexes: file_bracket_portproxy_v1_portproxy_proto_depIdxs,
		MessageInfos:      file_bracket_portproxy_v1_portproxy_proto_msgTypes,
	}.Build()
	File_bracket_portproxy_v1_portproxy_proto = out.File
	file_bracket_portproxy_v1_portproxy_proto_goTypes = nil
	file_bracket_portproxy_v1_portproxy_proto_depIdxs = nil
}
