// @dive-file: Portproxy gRPC contract for guest-side file, exec, shell, and daemon attachment services.
// @dive-rel: Generated by portproxy/build.rs and vmd/build.rs for guest runtime and node-local client use.
// @dive-rel: Defines streaming/daemon attach semantics used by distributed exec producer rebind paths.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: bracket/portproxy/v1/portproxy.proto

package portproxyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PortProxy_PrepareShutdown_FullMethodName = "/bracket.portproxy.v1.PortProxy/PrepareShutdown"
	PortProxy_ReadFile_FullMethodName        = "/bracket.portproxy.v1.PortProxy/ReadFile"
	PortProxy_WriteFile_FullMethodName       = "/bracket.portproxy.v1.PortProxy/WriteFile"
	PortProxy_ListDirectory_FullMethodName   = "/bracket.portproxy.v1.PortProxy/ListDirectory"
	PortProxy_DeletePath_FullMethodName      = "/bracket.portproxy.v1.PortProxy/DeletePath"
)

// PortProxyClient is the client API for PortProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortProxyClient interface {
	PrepareShutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListDirectory(ctx context.Context, in *ListDirectoryRequest, opts ...grpc.CallOption) (*ListDirectoryResponse, error)
	DeletePath(ctx context.Context, in *DeletePathRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type portProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewPortProxyClient(cc grpc.ClientConnInterface) PortProxyClient {
	return &portProxyClient{cc}
}

func (c *portProxyClient) PrepareShutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PortProxy_PrepareShutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portProxyClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, PortProxy_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portProxyClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PortProxy_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portProxyClient) ListDirectory(ctx context.Context, in *ListDirectoryRequest, opts ...grpc.CallOption) (*ListDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirectoryResponse)
	err := c.cc.Invoke(ctx, PortProxy_ListDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portProxyClient) DeletePath(ctx context.Context, in *DeletePathRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PortProxy_DeletePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortProxyServer is the server API for PortProxy service.
// All implementations must embed UnimplementedPortProxyServer
// for forward compatibility.
type PortProxyServer interface {
	PrepareShutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*emptypb.Empty, error)
	ListDirectory(context.Context, *ListDirectoryRequest) (*ListDirectoryResponse, error)
	DeletePath(context.Context, *DeletePathRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPortProxyServer()
}

// UnimplementedPortProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortProxyServer struct{}

func (UnimplementedPortProxyServer) PrepareShutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareShutdown not implemented")
}
func (UnimplementedPortProxyServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedPortProxyServer) WriteFile(context.Context, *WriteFileRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedPortProxyServer) ListDirectory(context.Context, *ListDirectoryRequest) (*ListDirectoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDirectory not implemented")
}
func (UnimplementedPortProxyServer) DeletePath(context.Context, *DeletePathRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePath not implemented")
}
func (UnimplementedPortProxyServer) mustEmbedUnimplementedPortProxyServer() {}
func (UnimplementedPortProxyServer) testEmbeddedByValue()                   {}

// UnsafePortProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortProxyServer will
// result in compilation errors.
type UnsafePortProxyServer interface {
	mustEmbedUnimplementedPortProxyServer()
}

func RegisterPortProxyServer(s grpc.ServiceRegistrar, srv PortProxyServer) {
	// If the following call panics, it indicates UnimplementedPortProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortProxy_ServiceDesc, srv)
}

func _PortProxy_PrepareShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortProxyServer).PrepareShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortProxy_PrepareShutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortProxyServer).PrepareShutdown(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortProxy_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortProxyServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortProxy_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortProxyServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortProxy_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortProxyServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortProxy_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortProxyServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortProxy_ListDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortProxyServer).ListDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortProxy_ListDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortProxyServer).ListDirectory(ctx, req.(*ListDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortProxy_DeletePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortProxyServer).DeletePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortProxy_DeletePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortProxyServer).DeletePath(ctx, req.(*DeletePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortProxy_ServiceDesc is the grpc.ServiceDesc for PortProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bracket.portproxy.v1.PortProxy",
	HandlerType: (*PortProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareShutdown",
			Handler:    _PortProxy_PrepareShutdown_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _PortProxy_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _PortProxy_WriteFile_Handler,
		},
		{
			MethodName: "ListDirectory",
			Handler:    _PortProxy_ListDirectory_Handler,
		},
		{
			MethodName: "DeletePath",
			Handler:    _PortProxy_DeletePath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bracket/portproxy/v1/portproxy.proto",
}

const (
	ShellExec_Exec_FullMethodName             = "/bracket.portproxy.v1.ShellExec/Exec"
	ShellExec_InteractiveShell_FullMethodName = "/bracket.portproxy.v1.ShellExec/InteractiveShell"
)

// ShellExecClient is the client API for ShellExec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShellExecClient interface {
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error)
	InteractiveShell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InteractiveShellRequest, InteractiveShellResponse], error)
}

type shellExecClient struct {
	cc grpc.ClientConnInterface
}

func NewShellExecClient(cc grpc.ClientConnInterface) ShellExecClient {
	return &shellExecClient{cc}
}

func (c *shellExecClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShellExec_ServiceDesc.Streams[0], ShellExec_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellExec_ExecClient = grpc.BidiStreamingClient[ExecRequest, ExecResponse]

func (c *shellExecClient) InteractiveShell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InteractiveShellRequest, InteractiveShellResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShellExec_ServiceDesc.Streams[1], ShellExec_InteractiveShell_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InteractiveShellRequest, InteractiveShellResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellExec_InteractiveShellClient = grpc.BidiStreamingClient[InteractiveShellRequest, InteractiveShellResponse]

// ShellExecServer is the server API for ShellExec service.
// All implementations must embed UnimplementedShellExecServer
// for forward compatibility.
type ShellExecServer interface {
	Exec(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error
	InteractiveShell(grpc.BidiStreamingServer[InteractiveShellRequest, InteractiveShellResponse]) error
	mustEmbedUnimplementedShellExecServer()
}

// UnimplementedShellExecServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShellExecServer struct{}

func (UnimplementedShellExecServer) Exec(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedShellExecServer) InteractiveShell(grpc.BidiStreamingServer[InteractiveShellRequest, InteractiveShellResponse]) error {
	return status.Error(codes.Unimplemented, "method InteractiveShell not implemented")
}
func (UnimplementedShellExecServer) mustEmbedUnimplementedShellExecServer() {}
func (UnimplementedShellExecServer) testEmbeddedByValue()                   {}

// UnsafeShellExecServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShellExecServer will
// result in compilation errors.
type UnsafeShellExecServer interface {
	mustEmbedUnimplementedShellExecServer()
}

func RegisterShellExecServer(s grpc.ServiceRegistrar, srv ShellExecServer) {
	// If the following call panics, it indicates UnimplementedShellExecServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShellExec_ServiceDesc, srv)
}

func _ShellExec_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShellExecServer).Exec(&grpc.GenericServerStream[ExecRequest, ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellExec_ExecServer = grpc.BidiStreamingServer[ExecRequest, ExecResponse]

func _ShellExec_InteractiveShell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShellExecServer).InteractiveShell(&grpc.GenericServerStream[InteractiveShellRequest, InteractiveShellResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellExec_InteractiveShellServer = grpc.BidiStreamingServer[InteractiveShellRequest, InteractiveShellResponse]

// ShellExec_ServiceDesc is the grpc.ServiceDesc for ShellExec service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShellExec_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bracket.portproxy.v1.ShellExec",
	HandlerType: (*ShellExecServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _ShellExec_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "InteractiveShell",
			Handler:       _ShellExec_InteractiveShell_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bracket/portproxy/v1/portproxy.proto",
}

const (
	DaemonManager_ExecDaemon_FullMethodName   = "/bracket.portproxy.v1.DaemonManager/ExecDaemon"
	DaemonManager_AttachDaemon_FullMethodName = "/bracket.portproxy.v1.DaemonManager/AttachDaemon"
)

// DaemonManagerClient is the client API for DaemonManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonManagerClient interface {
	ExecDaemon(ctx context.Context, in *ExecDaemonRequest, opts ...grpc.CallOption) (*ExecDaemonResponse, error)
	AttachDaemon(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachDaemonRequest, AttachDaemonResponse], error)
}

type daemonManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonManagerClient(cc grpc.ClientConnInterface) DaemonManagerClient {
	return &daemonManagerClient{cc}
}

func (c *daemonManagerClient) ExecDaemon(ctx context.Context, in *ExecDaemonRequest, opts ...grpc.CallOption) (*ExecDaemonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecDaemonResponse)
	err := c.cc.Invoke(ctx, DaemonManager_ExecDaemon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonManagerClient) AttachDaemon(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachDaemonRequest, AttachDaemonResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonManager_ServiceDesc.Streams[0], DaemonManager_AttachDaemon_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttachDaemonRequest, AttachDaemonResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonManager_AttachDaemonClient = grpc.BidiStreamingClient[AttachDaemonRequest, AttachDaemonResponse]

// DaemonManagerServer is the server API for DaemonManager service.
// All implementations must embed UnimplementedDaemonManagerServer
// for forward compatibility.
type DaemonManagerServer interface {
	ExecDaemon(context.Context, *ExecDaemonRequest) (*ExecDaemonResponse, error)
	AttachDaemon(grpc.BidiStreamingServer[AttachDaemonRequest, AttachDaemonResponse]) error
	mustEmbedUnimplementedDaemonManagerServer()
}

// UnimplementedDaemonManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonManagerServer struct{}

func (UnimplementedDaemonManagerServer) ExecDaemon(context.Context, *ExecDaemonRequest) (*ExecDaemonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecDaemon not implemented")
}
func (UnimplementedDaemonManagerServer) AttachDaemon(grpc.BidiStreamingServer[AttachDaemonRequest, AttachDaemonResponse]) error {
	return status.Error(codes.Unimplemented, "method AttachDaemon not implemented")
}
func (UnimplementedDaemonManagerServer) mustEmbedUnimplementedDaemonManagerServer() {}
func (UnimplementedDaemonManagerServer) testEmbeddedByValue()                       {}

// UnsafeDaemonManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonManagerServer will
// result in compilation errors.
type UnsafeDaemonManagerServer interface {
	mustEmbedUnimplementedDaemonManagerServer()
}

func RegisterDaemonManagerServer(s grpc.ServiceRegistrar, srv DaemonManagerServer) {
	// If the following call panics, it indicates UnimplementedDaemonManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonManager_ServiceDesc, srv)
}

func _DaemonManager_ExecDaemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecDaemonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonManagerServer).ExecDaemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonManager_ExecDaemon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonManagerServer).ExecDaemon(ctx, req.(*ExecDaemonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonManager_AttachDaemon_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DaemonManagerServer).AttachDaemon(&grpc.GenericServerStream[AttachDaemonRequest, AttachDaemonResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonManager_AttachDaemonServer = grpc.BidiStreamingServer[AttachDaemonRequest, AttachDaemonResponse]

// DaemonManager_ServiceDesc is the grpc.ServiceDesc for DaemonManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bracket.portproxy.v1.DaemonManager",
	HandlerType: (*DaemonManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecDaemon",
			Handler:    _DaemonManager_ExecDaemon_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AttachDaemon",
			Handler:       _DaemonManager_AttachDaemon_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bracket/portproxy/v1/portproxy.proto",
}
