// GENERATED by scripts/generate-esm-shim.mjs -- do not edit.
//
// ESM entry point. The implementation (and the native addon loader) is
// CommonJS; this re-exports it so `import { Runtime } from "chevalier"` works
// in ESM / "type": "module" projects without relying on named-export
// auto-detection. Regenerated on every build from index.js's actual exports.
import cjs from "./index.js";

export const {
  agentic,
  ChevalierError,
  createVfsGatewayServer,
  executeProgrammatic,
  McpClient,
  McpServer,
  programmaticToolDescription,
  Runtime,
  version,
  vfsContentHash,
  VfsContentHasher,
  VfsStorage,
} = cjs;
export default cjs;
